name: 'actions/checkout #1169'

on: push

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global --list
          echo "HOME: $HOME"
          cat "$HOME/.gitconfig"
