name: 'actions/checkout #1169'

on: push

jobs:

  checkout:
    runs-on: ubuntu-latest
    container:
      image: alpine/git:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"
          git commit --allow-empty -m "test"
      - run: |
          git config --global --list
          echo "HOME: $HOME"
          cat "$HOME/.gitconfig"
