name: 'actions/checkout #1169'

on: push

jobs:

  checkout:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$PWD"
      - run: echo "$GITHUB_WORKSPACE"
