name: Minimal example
on: push
jobs:
  commit:
    runs-on: ubuntu-latest
    container: alpine/git:latest
    steps:
      - name: Set up a Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - uses: actions/checkout@v3
      - name: Empty commit
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"
          git commit --allow-empty -m "test"
