name: Example workflow
on: pull_request
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "merge commit:"
          echo "github.sha=${{ github.sha }}"
          echo "base:"
          echo "github.base_ref=${{ github.base_ref }}"
          echo "github.event.pull_request.base.sha=${{ github.event.pull_request.base.sha }}"
          echo "head:"
          echo "github.head_ref=${{ github.head_ref }}"
          echo "github.event.pull_request.head.sha=${{ github.event.pull_request.head.sha }}"
