name: Mirror branch

on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror branch
        run: |
          git fetch origin preview
          git push origin mirror-branch:preview
